In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ram", "Shyam", "Hari", "Sita", "Gita",
        "Nabin", "Rita", "Bikash", "Anita", "Suman"
    ],

    # Categorical variables
    "Gender": [
        "Male", "Male", np.nan, "Female", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],  # 10% missing

    "City": [
        "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Kathmandu",
        "Pokhara", "Lalitpur", "Kathmandu", "Pokhara", np.nan
    ],  # 10% missing

    "Department": [
        "IT", np.nan, np.nan, "Finance", "IT",
        np.nan, "HR", np.nan, "IT", "Finance"
    ],  # 40% missing

    # Numerical variables
    "Age": [
        20, 22, np.nan, 21, 23,
        24, 25, 26, 22, 21
    ],  # 10% missing

    "Math": [
        80, 75, 90, np.nan, 85,
        78, 88, 92, 70, 95
    ],  # 10% missing

    "Salary": [
        30000, np.nan, np.nan, 40000, np.nan,
        35000, np.nan, 50000, np.nan, 38000
    ]  # 50% missing 
})


In [20]:
#fill categorical column by mode 
#fill numerical colum by mean useing SimpleImputer()
df_numeric = df.select_dtypes(include=["int64", "float64"]).columns
df_categorical = df.select_dtypes(include=["str"]).columns


In [21]:
#impute means filling 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy ="mean") #medain, most_frequent
imputerValue = imputer.fit_transform(df[df_numeric])#it imput each column by its impute
print(imputerValue)
df[df_numeric] =imputerValue
df




[[2.00000000e+01 8.00000000e+01 3.00000000e+04]
 [2.20000000e+01 7.50000000e+01 3.86000000e+04]
 [2.26666667e+01 9.00000000e+01 3.86000000e+04]
 [2.10000000e+01 8.36666667e+01 4.00000000e+04]
 [2.30000000e+01 8.50000000e+01 3.86000000e+04]
 [2.40000000e+01 7.80000000e+01 3.50000000e+04]
 [2.50000000e+01 8.80000000e+01 3.86000000e+04]
 [2.60000000e+01 9.20000000e+01 5.00000000e+04]
 [2.20000000e+01 7.00000000e+01 3.86000000e+04]
 [2.10000000e+01 9.50000000e+01 3.80000000e+04]]


,Name,Gender,City,Department,Age,Math,Salary
0,Ram,Male,Kathmandu,IT,20.000000,80.000000,30000.0
1,Shyam,Male,Pokhara,NaN,22.000000,75.000000,38600.0
2,Hari,NaN,Lalitpur,NaN,22.666667,90.000000,38600.0
3,Sita,Female,Bhaktapur,Finance,21.000000,83.666667,40000.0
4,Gita,Female,Kathmandu,IT,23.000000,85.000000,38600.0
5,Nabin,Male,Pokhara,NaN,24.000000,78.000000,35000.0
6,Rita,Female,Lalitpur,HR,25.000000,88.000000,38600.0
7,Bikash,Male,Kathmandu,NaN,26.000000,92.000000,50000.0
8,Anita,Female,Pokhara,IT,22.000000,70.000000,38600.0
9,Suman,Male,NaN,Finance,21.000000,95.000000,38000.0


In [22]:
#impute categorical 
catImputer = SimpleImputer(strategy="most_frequent")
catImputerValue = catImputer.fit_transform(df[df_categorical])
df[df_categorical] = catImputerValue
df

,Name,Gender,City,Department,Age,Math,Salary
0,Ram,Male,Kathmandu,IT,20.000000,80.000000,30000.0
1,Shyam,Male,Pokhara,IT,22.000000,75.000000,38600.0
2,Hari,Male,Lalitpur,IT,22.666667,90.000000,38600.0
3,Sita,Female,Bhaktapur,Finance,21.000000,83.666667,40000.0
4,Gita,Female,Kathmandu,IT,23.000000,85.000000,38600.0
5,Nabin,Male,Pokhara,IT,24.000000,78.000000,35000.0
6,Rita,Female,Lalitpur,HR,25.000000,88.000000,38600.0
7,Bikash,Male,Kathmandu,IT,26.000000,92.000000,50000.0
8,Anita,Female,Pokhara,IT,22.000000,70.000000,38600.0
9,Suman,Male,Kathmandu,Finance,21.000000,95.000000,38000.0
