In [70]:
#columns =[Age,Math_marks, Science_marks]
import numpy as np


data = np.array([
    [18,35,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [79]:
total_sum = data.sum(axis=0)
total_sum
data= np.vstack((data, total_sum))
data

array([[ 18,  35,  78],
       [ 19,  92,  88],
       [ 17,  76,  95],
       [ 18,  65,  70],
       [ 20,  90,  85],
       [ 92, 358, 416],
       [184, 716, 832]])

In [72]:
#Replace all Science marks less than80 withh 0
# data[:,2]   = [ 0 if el<80 else el for el in data[:,2]]
# data

In [73]:
df_total = data[:,1]+data[:,2]
df_total

array([113, 180, 171, 135, 175])

In [74]:
np.column_stack((data, df_total))

array([[ 18,  35,  78, 113],
       [ 19,  92,  88, 180],
       [ 17,  76,  95, 171],
       [ 18,  65,  70, 135],
       [ 20,  90,  85, 175]])

In [1]:
700000/6


116666.66666666667